### ISSUE TITLE
About the training code

### ISSUE THREAD

**Issue by howardgriffin** [showlab/Show-1#5]
Nice work! 
Would you be like to release the training code? I want to finetune the model on my own dataset. 
Thank you!

**Comment by junhaozhang98** [comment]
Unfortunately, we are not planninig  to release training code.  But training code pipeline is quite similar or even same as Tune a Video  if you use the single node machine. The only difference is using a couple of videos instead of a single video.  Hope it helps. https://github.com/showlab/Tune-A-Video

**Comment by junhaozhang98** [comment]
Or you can refer this link https://github.com/showlab/MotionDirector. We will release training video lora code soon.

**Comment by howardgriffin** [comment]
Thank you!
