### ISSUE TITLE
Is there a specific reason why DeepFloyd is chosen as T2I prior?

### ISSUE THREAD

**Issue by Ground-A-Video** [showlab/Show-1#6]
Thank you open-sourcing such an amazing work!
This will make the video community even more vibrant.

Is there a specific reason why **DeepFloyd** is chosen for the pixel-based key frame generation model, instead of **Stable Diffusion**?
Is it because DeepFloyd supports generating images in low spatial dimensions and DeepFloyd is more expert in generating images with low-spatial dimensions?

**Comment by junhaozhang98** [comment]
Thanks for your comments and questions. Yes! Because DeepFloyd has a more precise text control thanks to both large T5 encoder and low resolution pixel sapce.

**Comment by junhaozhang98** [comment]
Thanks for your comments!  Hotshotco is great!! But Deepfloyd, especially its XL model,  has more precise text control than SDXL. Currently, our university resource only support us to train small deepfloyd L model.

Meanwhile, for sr2 stage, we can replace any latent video diffusion e.g., hotshotco with the  original one for superresolution.  We propose the overall framework instead of a single model.
